// <auto-generated />
using System;
using ClinicApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicApp.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    partial class ClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicApp.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Respiratory",
                            Code = "J00",
                            Name = "Common Cold"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cardiovascular",
                            Code = "I10",
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Endocrine",
                            Code = "E11",
                            Name = "Type 2 Diabetes"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mental Health",
                            Code = "F41.9",
                            Name = "Anxiety Disorder"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Neurological",
                            Code = "G43",
                            Name = "Migraine"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Gastrointestinal",
                            Code = "K29",
                            Name = "Gastritis"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Respiratory",
                            Code = "J30",
                            Name = "Allergic Rhinitis"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Musculoskeletal",
                            Code = "M54.5",
                            Name = "Lower Back Pain"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Dermatological",
                            Code = "L30",
                            Name = "Eczema"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Genitourinary",
                            Code = "N39.0",
                            Name = "Urinary Tract Infection"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Respiratory",
                            Code = "J40",
                            Name = "Bronchitis"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Mental Health",
                            Code = "F32",
                            Name = "Depression"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Musculoskeletal",
                            Code = "M15",
                            Name = "Osteoarthritis"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Respiratory",
                            Code = "J45",
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Nutritional",
                            Code = "E55",
                            Name = "Vitamin D Deficiency"
                        });
                });

            modelBuilder.Entity("ClinicApp.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ExaminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsExamined")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prescriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedDiagnoses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicApp.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Symptoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Name = "Fever"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Neurological",
                            Name = "Headache"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Respiratory",
                            Name = "Cough"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Respiratory",
                            Name = "Shortness of breath"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cardiovascular",
                            Name = "Chest pain"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Gastrointestinal",
                            Name = "Nausea"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Gastrointestinal",
                            Name = "Vomiting"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Gastrointestinal",
                            Name = "Diarrhea"
                        },
                        new
                        {
                            Id = 9,
                            Category = "General",
                            Name = "Fatigue"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Neurological",
                            Name = "Dizziness"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Musculoskeletal",
                            Name = "Joint pain"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Musculoskeletal",
                            Name = "Back pain"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Dermatological",
                            Name = "Skin rash"
                        },
                        new
                        {
                            Id = 14,
                            Category = "General",
                            Name = "Insomnia"
                        },
                        new
                        {
                            Id = 15,
                            Category = "General",
                            Name = "Weight loss"
                        });
                });

            modelBuilder.Entity("ClinicApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 30, 18, 49, 51, 499, DateTimeKind.Utc).AddTicks(2682),
                            Email = "admin@hospital.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            Password = "$2a$11$JVglH0ppou62UragLOHhCOVQrow0Hi4mHtIsE8cq1tjJo81PrWNjG",
                            Role = 1,
                            Username = "Adnaan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
